version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./docs:/data/docs
      - ./chromadb:/data/chroma
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Make sure to set this in your host env
    command: python manage.py runserver 0.0.0.0:8000
